export const timeZones = [
  { value: 'America/Los_Angeles', label: 'Pacific Time - US/Canada' },
  { value: 'America/Vancouver', label: 'Pacific Time - Canada' },
  { value: 'America/Denver', label: 'Mountain Time - US & Canada' },
  { value: 'America/Phoenix', label: 'Mountain Time - Arizona' },
  { value: 'America/Chicago', label: 'Central Time - US/Canada' },
  { value: 'America/Mexico_City', label: 'Central Time - Mexico' },
  { value: 'America/New_York', label: 'Eastern Time - US/Canada' },
  { value: 'America/Toronto', label: 'Eastern Time - Canada' },
  { value: 'America/Halifax', label: 'Atlantic Time - Canada' },
  { value: 'America/St_Johns', label: 'Newfoundland Time - Canada' },
  { value: 'America/Anchorage', label: 'Alaska Time' },
  { value: 'Pacific/Honolulu', label: 'Hawaii Time' },

  // South America
  { value: 'America/Sao_Paulo', label: 'São Paulo Time - Brazil' },
  { value: 'America/Buenos_Aires', label: 'Buenos Aires Time - Argentina' },
  { value: 'America/Santiago', label: 'Santiago Time - Chile' },
  { value: 'America/Lima', label: 'Lima Time - Peru' },
  { value: 'America/Bogota', label: 'Bogota Time - Colombia' },

  // Europe
  { value: 'Europe/London', label: 'London Time - UK' },
  { value: 'Europe/Dublin', label: 'Dublin Time - Ireland' },
  { value: 'Europe/Paris', label: 'Paris Time - France' },
  { value: 'Europe/Berlin', label: 'Berlin Time - Germany' },
  { value: 'Europe/Rome', label: 'Rome Time - Italy' },
  { value: 'Europe/Madrid', label: 'Madrid Time - Spain' },
  { value: 'Europe/Amsterdam', label: 'Amsterdam Time - Netherlands' },
  { value: 'Europe/Brussels', label: 'Brussels Time - Belgium' },
  { value: 'Europe/Stockholm', label: 'Stockholm Time - Sweden' },
  { value: 'Europe/Oslo', label: 'Oslo Time - Norway' },
  { value: 'Europe/Copenhagen', label: 'Copenhagen Time - Denmark' },
  { value: 'Europe/Helsinki', label: 'Helsinki Time - Finland' },
  { value: 'Europe/Warsaw', label: 'Warsaw Time - Poland' },
  { value: 'Europe/Prague', label: 'Prague Time - Czech Republic' },
  { value: 'Europe/Vienna', label: 'Vienna Time - Austria' },
  { value: 'Europe/Budapest', label: 'Budapest Time - Hungary' },
  { value: 'Europe/Zurich', label: 'Zurich Time - Switzerland' },

  // Asia
  { value: 'Asia/Dubai', label: 'Dubai Time - UAE' },
  { value: 'Asia/Riyadh', label: 'Riyadh Time - Saudi Arabia' },
  { value: 'Asia/Jerusalem', label: 'Jerusalem Time - Israel' },
  { value: 'Asia/Istanbul', label: 'Istanbul Time - Turkey' },
  { value: 'Asia/Moscow', label: 'Moscow Time - Russia' },
  { value: 'Asia/Kolkata', label: 'India Time' },
  { value: 'Asia/Calcutta', label: 'India Time' },
  { value: 'Asia/Dhaka', label: 'Dhaka Time - Bangladesh' },
  { value: 'Asia/Bangkok', label: 'Bangkok Time - Thailand' },
  { value: 'Asia/Singapore', label: 'Singapore Time' },
  { value: 'Asia/Hong_Kong', label: 'Hong Kong Time' },
  { value: 'Asia/Shanghai', label: 'China Time' },
  { value: 'Asia/Seoul', label: 'Seoul Time - Korea' },
  { value: 'Asia/Tokyo', label: 'Tokyo Time - Japan' },
  { value: 'Asia/Manila', label: 'Manila Time - Philippines' },

  // Oceania
  { value: 'Australia/Sydney', label: 'Sydney Time - Australia' },
  { value: 'Australia/Melbourne', label: 'Melbourne Time - Australia' },
  { value: 'Australia/Brisbane', label: 'Brisbane Time - Australia' },
  { value: 'Australia/Adelaide', label: 'Adelaide Time - Australia' },
  { value: 'Australia/Perth', label: 'Perth Time - Australia' },
  { value: 'Pacific/Auckland', label: 'Auckland Time - New Zealand' },

  // Africa
  { value: 'Africa/Cairo', label: 'Cairo Time - Egypt' },
  { value: 'Africa/Johannesburg', label: 'Johannesburg Time - South Africa' },
  { value: 'Africa/Nairobi', label: 'Nairobi Time - Kenya' },
  { value: 'Africa/Lagos', label: 'Lagos Time - Nigeria' },
  { value: 'Africa/Casablanca', label: 'Casablanca Time - Morocco' }
]
